python cruise.py 0 10 b cruiseCounter.csv
python cruise.py 0 20 b cruiseCounter.csv
python cruise.py 0 30 b cruiseCounter.csv
python cruise.py 0 40 b cruiseCounter.csv
python cruise.py 0 50 b cruiseCounter.csv
python cruise.py 0 60 b cruiseCounter.csv
python cruise.py 0 70 b cruiseCounter.csv
python cruise.py 0 80 b cruiseCounter.csv
python cruise.py 0 90 b cruiseCounter.csv
python cruise.py 0 100 b cruiseCounter.csv

python cruise.py 2 10 b cruiseCounter.csv
python cruise.py 2 20 b cruiseCounter.csv
python cruise.py 2 30 b cruiseCounter.csv
python cruise.py 2 40 b cruiseCounter.csv
python cruise.py 2 50 b cruiseCounter.csv
python cruise.py 2 60 b cruiseCounter.csv
python cruise.py 2 70 b cruiseCounter.csv
python cruise.py 2 80 b cruiseCounter.csv
python cruise.py 2 90 b cruiseCounter.csv
python cruise.py 2 100 b cruiseCounter.csv
