python getTrajectories.py 5 0 d nm True trajectoryTime.csv
python getTrajectories.py 10 0 d nm True trajectoryTime.csv
python getTrajectories.py 15 0 d nm True trajectoryTime.csv
python getTrajectories.py 20 0 d nm True trajectoryTime.csv
python getTrajectories.py 25 0 d nm True trajectoryTime.csv
python getTrajectories.py 30 0 d nm True trajectoryTime.csv
python getTrajectories.py 40 0 d nm True trajectoryTime.csv
python getTrajectories.py 60 0 d nm True trajectoryTime.csv
python getTrajectories.py 80 0 d nm True trajectoryTime.csv
python getTrajectories.py 90 0 d nm True trajectoryTime.csv
python getTrajectories.py 100 0 d nm True trajectoryTime.csv
python getTrajectories.py 110 0 d nm True trajectoryTime.csv
python getTrajectories.py 120 0 d nm True trajectoryTime.csv
python getTrajectories.py 140 0 d nm True trajectoryTime.csv
python getTrajectories.py 150 0 d nm True trajectoryTime.csv
python getTrajectories.py 160 0 d nm True trajectoryTime.csv
python getTrajectories.py 180 0 d nm True trajectoryTime.csv
python getTrajectories.py 200 0 d nm True trajectoryTime.csv

