python cruise.py 3 10 b cruiseCounter3.csv
python cruise.py 3 20 b cruiseCounter3.csv
python cruise.py 3 30 b cruiseCounter3.csv
python cruise.py 3 40 b cruiseCounter3.csv
python cruise.py 3 50 b cruiseCounter3.csv
python cruise.py 3 60 b cruiseCounter3.csv
python cruise.py 3 70 b cruiseCounter3.csv
python cruise.py 3 80 b cruiseCounter3.csv
python cruise.py 3 90 b cruiseCounter3.csv
python cruise.py 3 100 b cruiseCounter3.csv

python cruise.py 4 10 b cruiseCounter4.csv
python cruise.py 4 20 b cruiseCounter4.csv
python cruise.py 4 30 b cruiseCounter4.csv
python cruise.py 4 40 b cruiseCounter4.csv
python cruise.py 4 50 b cruiseCounter4.csv
python cruise.py 4 60 b cruiseCounter4.csv
python cruise.py 4 70 b cruiseCounter4.csv
python cruise.py 4 80 b cruiseCounter4.csv
python cruise.py 4 90 b cruiseCounter4.csv
python cruise.py 4 100 b cruiseCounter4.csv
