python testSpeed.py e 0
python testSpeed.py e 2
python testSpeed.py e 4
python testSpeed.py e 6
python testSpeed.py e 8
python testSpeed.py e 10
python testSpeed.py e 12
python testSpeed.py e 14
python testSpeed.py e 16
python testSpeed.py e 18
python testSpeed.py e 20
python testSpeed.py e 22
python testSpeed.py e 24
python testSpeed.py e 26
python testSpeed.py e 28
python testSpeed.py e 30
python testSpeed.py e 32
python testSpeed.py e 34
python testSpeed.py e 36
python testSpeed.py e 38
python testSpeed.py e 40
python testSpeed.py e 42
python testSpeed.py e 44
python testSpeed.py e 46
python testSpeed.py e 48
