python inRangeOfTl.py 10 b TlCounter.csv
python inRangeOfTl.py 20 b TlCounter.csv
python inRangeOfTl.py 30 b TlCounter.csv
python inRangeOfTl.py 40 b TlCounter.csv
python inRangeOfTl.py 50 b TlCounter.csv
python inRangeOfTl.py 60 b TlCounter.csv
python inRangeOfTl.py 70 b TlCounter.csv
python inRangeOfTl.py 80 b TlCounter.csv
python inRangeOfTl.py 90 b TlCounter.csv
python inRangeOfTl.py 100 b TlCounter.csv
python inRangeOfTl.py 110 b TlCounter.csv
python inRangeOfTl.py 120 b TlCounter.csv
python inRangeOfTl.py 130 b TlCounter.csv
python inRangeOfTl.py 140 b TlCounter.csv
python inRangeOfTl.py 150 b TlCounter.csv
