python idle.py d 0  Test 
python idle.py d 10 Test 
python idle.py d 20 Test 
python idle.py d 30 Test 
python idle.py d 40 Test 
python idle.py d 50 Test 
python idle.py d 60 Test 
python idle.py d 70 Test 
python idle.py d 80 Test 
python idle.py d 90 Test 
python idle.py d 100 Test 
python idle.py d 110 Test 
python idle.py d 120 Test 
python idle.py d 150 Test 
python idle.py d 200 Test 
python idle.py d 250 Test 
python idle.py d 300 Test 
python idle.py d 350 Test 
python idle.py d 400 Test 
python idle.py d 450 Test 
python idle.py d 500 Test 
python idle.py d 600 Test 
python idle.py d 700 Test 
python idle.py d 800 Test 
python idle.py d 900 Test 
python idle.py d 1000 Test 
python idle.py d 1100 Test 
