python getTrajectories.py 5 0 f nm True trajectoryTime.csv
python getTrajectories.py 10 0 f nm True trajectoryTime.csv
python getTrajectories.py 15 0 f nm True trajectoryTime.csv
python getTrajectories.py 20 0 f nm True trajectoryTime.csv
python getTrajectories.py 25 0 f nm True trajectoryTime.csv
python getTrajectories.py 30 0 f nm True trajectoryTime.csv
python getTrajectories.py 40 0 f nm True trajectoryTime.csv
python getTrajectories.py 60 0 f nm True trajectoryTime.csv
python getTrajectories.py 80 0 f nm True trajectoryTime.csv
python getTrajectories.py 90 0 f nm True trajectoryTime.csv
python getTrajectories.py 100 0 f nm True trajectoryTime.csv
python getTrajectories.py 110 0 f nm True trajectoryTime.csv
python getTrajectories.py 120 0 f nm True trajectoryTime.csv
python getTrajectories.py 140 0 f nm True trajectoryTime.csv
python getTrajectories.py 150 0 f nm True trajectoryTime.csv
python getTrajectories.py 160 0 f nm True trajectoryTime.csv
python getTrajectories.py 180 0 f nm True trajectoryTime.csv
python getTrajectories.py 200 0 f nm True trajectoryTime.csv

